15 warnings generated.
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:16:5: warning: 'else' is required after 'if' [bsl-else-required-after-if]
    if (x) {
    ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:21:5: warning: 'else' is required after 'if' [bsl-else-required-after-if]
    if (x) {
    ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:23:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (y) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:30:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (y) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:43:5: warning: 'else' is required after 'if' [bsl-else-required-after-if]
    if (x) {
    ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:52:5: warning: 'else' is required after 'if' [bsl-else-required-after-if]
    if (x) {
    ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:63:9: warning: 'else' is required after 'if' or add bsl::touch() after `if` [bsl-else-required-after-if]
        if (y) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:72:5: warning: 'else' is required after 'if' [bsl-else-required-after-if]
    if (x) {
    ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:77:14: warning: do not use 'else' after 'return/continue/break' [bsl-else-required-after-if]
        else {
             ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:92:9: warning: 'else' is required after 'if' or add bsl::touch() after `if` [bsl-else-required-after-if]
        if (x) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:99:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (x) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:106:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (x) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:132:9: warning: 'else' is required after 'if' or add bsl::touch() after `if` [bsl-else-required-after-if]
        if (x) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:139:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (x) {
        ^
/home/quinnr/working/llvm-project/clang-tools-extra/test/clang-tidy/bsl-tmp.cpp:146:9: warning: 'else' is required after 'if' [bsl-else-required-after-if]
        if (x) {
        ^
